- name : Jazda
  hosts: all
  tasks:
  - name: Unpack my file
    win_dsc5:
      resource_name="archive"
      ensure="Present"
      path="C:\Temp\zipfile.zip"
      destination="C:\Temp\Temp2"


- name : Create FIle
  hosts: all
  tasks:
  - name: Unpack my file
    win_file:
      path=c:\testAnsible
      state=directory
        